In [1]:
my_list = [10, 'apple', 3.5]
for item in my_list:
    print(f"{item} is at memory address {id(item)}")


10 is at memory address 1628389638672
apple is at memory address 1628484658736
3.5 is at memory address 1628465342128


In [5]:
print(id(my_list))

1628484662464


In [ ]:
What is a 2-D list and 3-D list

In [ ]:
[[1,2,3],[4,5,6]] - 2-D list 
[[[1,2,3],[4,5,6]]]
[[[1,2],[3,4]],[[5,6],[7,8]]]

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
c = np.arange(1,10,2)
print(c)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [15]:
alpha = b.reshape(2,5)
print(alpha)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [7]:
import numpy as np
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(1,9,dtype = float)

array([1., 2., 3., 4., 5., 6., 7., 8.])

Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print('Break')
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Break
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Arithmetic operations on numpy arrays

In [21]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [22]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [23]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [24]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

Relational operations on numpy arrays

In [25]:
a2>12

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Vector operations on numpy arrays

In [26]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [27]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [28]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [29]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

Array Functions

In [39]:
omega = np.random.random((3,3))
omega = np.round(omega*100)
omega


array([[75., 67., 54.],
       [69.,  6., 71.],
       [80., 86., 67.]])

In [40]:
np.max(omega)

np.float64(86.0)

In [41]:
np.min(omega)

np.float64(6.0)

In [42]:
np.sum(omega)

np.float64(575.0)

In [43]:
np.prod(omega)

np.float64(3676645493424000.0)

In [46]:
np.mean(omega,axis = 1)

array([65.33333333, 48.66666667, 77.66666667])

In [48]:
np.median(omega)

np.float64(69.0)

In [51]:
np.median(omega,axis = 1)

array([67., 69., 80.])

In [52]:
np.std(omega)

np.float64(22.153226223256183)

In [ ]:
import numpy as np
b1 = np.arange(10)
b2 = np.arange(12).reshape(3,4)
b3 = np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

To locate a particular element in b1 

In [10]:
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b1[0]

np.int64(0)

In [9]:
b1[-1]

np.int64(9)

In [11]:
b1[-2]

np.int64(8)

In [ ]:
To locate a particular element in b2
Suppose access two elements from b2 which are 2 and 10

In [12]:
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
b2[0,2]

np.int64(2)

In [14]:
b2[2,2]

np.int64(10)

Now if i want to print a particular row and particular column suppose row 2nd and column 3rd

In [15]:
b2[1,:]

array([4, 5, 6, 7])

In [16]:
b2[:,2]

array([ 2,  6, 10])

Note - It can be clearly seen that in b1 only one index is reqired to access an element while in b2 two index are required thus b1 is 1d array and b2 is 2d array 

Suppose access two elements in b3 which are 1 and 6

In [17]:
b3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
b3[0,0,1]

np.int64(1)

In [19]:
b3[1,1,0]

np.int64(6)

In [ ]:
Slicing in numpy arrays

In [ ]:
Suppose we want to access 2,3, 4 from b1

In [21]:
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b1[2:5]

array([2, 3, 4])

In [ ]:
Next print a matrix out of the array b2 5,6,9,10

In [23]:
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
b2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

Suppose I want 0 3 8 11 printed in a matrix from  

In [26]:
b2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

Suppose I want 1 3 9 11 printed in a matrix from  

In [27]:
b2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

Suppose I want 1 3 9 11 printed in a matrix from  

In [28]:
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b2[1,::3]

array([4, 7])

Suppose I want 1 2 3 5 6 7 printed in a matrix from  

In [30]:
b2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])